name: new_portfolio_WebSite
description: A new portfolio website.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.4
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.4
  auto_size_text: ^3.0.0
  expandable_page_view: ^1.0.17
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.14
  flutter_html: ^3.0.0-beta.2

flutter_gen:
  output: lib/gen/
  line_length: 80

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/about/
    - assets/images/skills/
    - assets/images/works/works_thumbnail/
    - assets/images/works/works_detail/
    - assets/logos/
  fonts:
    - family: Schyler
      fonts:
         - asset: fonts/Ubuntu-L.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

